services:
  postgres_finance:
    image: postgres:latest
    container_name: postgres_finance
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_FINANCE}
    ports:
      - '5434:5432' # local:container
    volumes:
      - ./data/finance:/var/lib/postgresql/data
    restart: unless-stopped

  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    ports:
      - '5433:5432'
    volumes:
      - ./data/test:/var/lib/postgresql/data
    restart: unless-stopped
